### ISSUE TITLE
How to uncompress the files to create .shp file ?

### ISSUE THREAD

**Issue by abhilashchowdhary** [justinelliotmeyers/INDIA_2018_DISTRICTS#1]

**Comment by justinelliotmeyers** [comment]
Download free rar software and extract. Thanks!

**Comment by abhilashchowdhary** [comment]
For anyone having issues converting these to geojson
On unix/OSx : 
`cat DISTRICTS_2018.shp.z01 > DISTRICTS_2018_full.shp.zip`
`cat DISTRICTS_2018.shp.z02 >> DISTRICTS_2018_full.shp.zip`
`cat DISTRICTS_2018.shp.z03 >> DISTRICTS_2018_full.shp.zip`
`cat DISTRICTS_2018.shp.z04 >> DISTRICTS_2018_full.shp.zip`
`cat DISTRICTS_2018.shp.zip >> DISTRICTS_2018_full.shp.zip`
`unzip DISTRICTS_2018_full.shp.zip`
`unzip DISTRICTS_2018.cpg.zip`
`unzip DISTRICTS_2018.prj.zip`
`unzip DISTRICTS_2018.sbx.zip`
`unzip DISTRICTS_2018.dbf.zip`
`unzip DISTRICTS_2018.sbn.zip`
`unzip DISTRICTS_2018.shx.zip`

Converting to GeoJSON:
`ogr2ogr -f GeoJSON DISTRICTS_2018_full.geojson DISTRICTS_2018_full.shp`
